### ISSUE TITLE
python-rtmbotへの移行

### ISSUE THREAD

**Issue by odanado** [ShotaKitazawa/slack-emoji-register-bot#5]
https://github.com/slackapi/python-rtmbot を使ってコードを機能ごとに分割したい

**Comment by ShotaKitazawa** [comment]
publicに変更しました〜

書きたいですね！サブコマンドやbottun選択を実装しながらそっちも出来たらと思います！ (が当分遅くなってしまいそうです←)

**Comment by odanado** [comment]
変更ありがとうございます

一旦このissueはクローズします
紹介記事をどうするかについては別のissueで相談しましょう！
